package ir.khalili.products.odds.core.client;

import java.io.BufferedReader;
import java.io.InputStreamReader;

import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.config.RequestConfig;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.HttpClientBuilder;

import io.vertx.core.json.JsonObject;

/**
 * @author A.KH
 */
public class CallQuestion {

	public static final String user = "caspUser";
	public static final String pass = "casp456";

	private static HttpClient httpClient = HttpClientBuilder.create()
			.setDefaultRequestConfig(RequestConfig.custom().setConnectTimeout(20 * 1000).build()).build();

	public static void main(String[] args) {

		try {

			JsonObject joInput = new JsonObject();
			joInput.put("serviceNumber", "09120590480");
			joInput.put("serviceType", 2);
			joInput.put("identificationType", 0);
			joInput.put("identificationNo", "0082740453");
			
//			HttpPost request = new HttpPost("https://sandbox.parsian-bank.ir/shahkar-gateway/1.0/serviceID-matching");
			HttpPost request = new HttpPost("http://intranetsecure.parsian-bank.ir/shahkar-gateway/serviceID-matching");
			request.setHeader("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiI4Mzk3MzMxNzI0NzM3MjI2Iiwic2NvcGUiOlsiZ2V0Q2FydGFibGVCYXRjaFRyYW5zZmVyUmVxdWVzdERldGFpbCIsImFjY2VwdEFjaFRyYW5zZmVyIiwiYWNoQmF0Y2hUcmFuc2ZlciIsImdldEJsb2NrZWREZXBvc2l0c0xpc3QiLCJnZXRQYXltZW50U2VydmljZXNCeVR5cGUiLCJpbmNyZWFzZVByZXZpb3VzQmxvY2tEZXBvc2l0QW1vdW50IiwiZGVjbGFyZVVzZWRSZWZlcmVuY2VDb2RlcyIsImdldEJpbGxJbmZvIiwiaWJhbkVucXVpcnkiLCJtdW5HZXRPZGRFdmVuUmF0aW9uaW5nWm9uZSIsImFkZFBlcmlvZGljQmlsbFJlcXVlc3QiLCJ2ZXJpZnlUcmFuc2FjdGlvbiIsIm9wZW5EZXBvc2l0IiwicmVnaXN0ZXJDYXJ0YWJsZUJhdGNoQWNoT3JkZXJSZXF1ZXN0IiwicGljaGFrSW5xdWlyeUNoZXF1ZSIsImNhbGN1bGF0ZUNlcnRhaW5seUxvYW5JbnRlcmVzdCIsImJsb2NrUGFydGlhbERlcG9zaXRXaXRoSnVyaWRpY2FsT3JkZXIiLCJtYXRjaE5hdGlvbmFsTm9BbmRDYXJkTm9BbmRNb2JpbGVObyIsImNyZWF0ZU1vZGVybkdhdGV3YXlVc2VyIiwiZ2V0UGF5bWVudEJpbGxTdGF0ZW1lbnQiLCJnZXRCYW5rcyIsImV4dGVuZFNNU1NldHRpbmciLCJtdW5DYWxjdWxhdGVEZWJ0QnVpbGRCaWxsIiwicmVqZWN0Q2FydGFibGVSZXF1ZXN0IiwiZG9DYXJ0YWJsZVJlcXVlc3QiLCJjYW5jZWxBY2hUcmFuc2FjdGlvbiIsImFjdGl2YXRlSUdhcFB1c2hOb3RpZmljYXRpb251c2VyIiwidHJhbnNsYXRlRXhjZXB0aW9uIiwiZ2V0RGVzdGluYXRpb25DYXJkT3duZXIiLCJnZXRTaWduZWREZXBvc2l0cyIsImNhcmRMZXNzSXNzdWVWb3VjaGVyIiwicGdBY2hOb3JtYWxUcmFuc2ZlciIsInZhbGlkYXRpb25SZWZlcmVuY2VDb2RlIiwicGVyc2lhbkN1c3RvbWVyQ2x1YkRlQWN0aXZhdGlvbiIsImdldENhcmRUcmFuc2FjdGlvbnMiLCJkaXNhYmxlVHJhbnNmZXIiLCJjaGVja1BhaWRCaWxsIiwibXVuQWlyUG9sbHV0aW9uUXVvdGEiLCJnZXREZWZhdWx0QmlsbFN0YXRlbWVudCIsImdldENhcnRhYmxlVHJhbnNmZXJSZXF1ZXN0RGV0YWlsIiwicGFpZENoYXJnZUxpc3QiLCJnZXRCYXRjaEJpbGxJbmZvIiwicGljaGFrVHJhbnNmZXJDaGVxdWUiLCJzdXNwZW5kQWNoVHJhbnNhY3Rpb24iLCJnZXRHdWFyYW50eUxpc3QiLCJnZXRDdXN0b21lckFkZHJlc3MiLCJydGdzVHJhbnNmZXJSZXBvcnQiLCJzaWduUmVxdWVzdERldGFpbHMiLCJkZWFjdGl2YXRlSUdhcFB1c2hOb3RpZmljYXRpb25Vc2VyIiwidXBkYXRlRmF2b3JpdGVBY2NvdW50U2V0dGluZyIsImlucXVpcnlOYXR1cmFsUGVyc29uT3BlblNpbmdsZURlcG9zaXQiLCJnZXRDdXN0b21lckluZm9MaXN0QnlNb2RpZnlEYXRlIiwidG9wdXBDaGFyZ2VGcm9tVmlydHVhbFRlcm1pbmFsIiwiZ2V0Q3JlZGl0QmlsbFRyYW5zYWN0aW9ucyIsImdldEJyYW5jaEFsbG93ZWREZXBvc2l0c1RvT3BlbiIsImdldE1vZGVybkdhdGV3YXlVc2VySW5mbyIsIndhcm1pbmdDYXJkIiwiaW5zdGl0dXRpb25hbFRyYW5zZmVyIiwibm9ybWFsVHJhbnNmZXIiLCJpbnF1aXJ5Q2FyZElzc3VpbmciLCJibG9ja1RvdGFsRGVwb3NpdFdpdGhKdXJpZGljYWxPcmRlciIsInNlYXJjaFRoaXJkUGFydHkiLCJkb0N1c3RvbVJldHJ1biIsInVwZGF0ZVVzZXJCaWxsU2V0dGluZyIsImdldEJlT3BlbmVkRGVwb3NpdHMiLCJzd2l0Y2hGdW5kVHJhbnNmZXJGcm9tVmlydHVhbFRlcm1pbmFsIiwiZ2V0TG9hbkRldGFpbCIsImludGVybmFsTm9ybWFsVHJhbnNmZXIiLCJ1cGRhdGVEZWZhdWx0Q29udGFjdEluZm8iLCJwYXlCYXRjaEJpbGwiLCJwYXlMb2FuIiwicnRnc05vcm1hbFRyYW5zZmVyIiwiYWNoTm9ybWFsVHJhbnNmZXIiLCJnZXRDdXN0b21lckluZm8iLCJjb252ZXJ0Q2FyZFRvSWJhbiIsImdldENyZWRpdEJpbGxzIiwicnRnc1RyYW5zZmVyRGV0YWlsUmVwb3J0IiwiZGVwb3NpdFZlcmlmaWNhdGlvbkJ5TmF0aW9uYWxDb2RlIiwiY3JlYXRlTmF0dXJhbEN1c3RvbWVyIiwibmF0dXJhbFBlcnNvbk9wZW5TaW5nbGVEZXBvc2l0IiwibXVuVHJhZmZpY1BsYXRlUGF5IiwibXVuR2V0VHJhZmZpY1BsYW5ab25lIiwicGF5QmlsbEJ5QWNjb3VudCIsImNhcmRJbmZvUmV0cmlldmF0aW9uIiwiY2FyZFNldFBhc3N3b3JkIiwiZ2V0RGVwb3NpdE93bmVyTmFtZSIsImdldEluc3RpdHV0aW9ucyIsIm11blRyYWZmaWNQYXlMb2ciLCJnZXRNZXJjaGFudEluZm8iLCJzZXJ2aWNlSURfbWF0Y2hpbmciLCJjYXJkVHJhbnNmZXIiLCJnZXRDaGVxdWUiLCJnZXRCcmFuY2hCYWxhbmNlIiwibWF0Y2hOYXRpb25hbENvZGVXaXRoQ2FyZE5vIiwiZ2V0Q3VzdG9tZXJTaWduYXR1cmVzIiwicmVnaXN0ZXJDYXJ0YWJsZUFjaE9yZGVyUmVxdWVzdCIsInBpY2hha0FjY2VwdENoZXF1ZSIsInN1c3BlbmRBY2hUcmFuc2ZlciIsInNldE1vZGVybkdhdGV3YXlTZXJ2aWNlTGltaXRhdGlvbiIsInJlcG9ydEFjaFRyYW5zZmVyU3VtbWFyeSIsImludGVybmFsT3BlbkRlcG9zaXQiLCJidXlTbXNQcm9maWxlU2V0dGluZyIsImNhcmRJc3N1aW5nIiwiYXBwcm92ZUNhcnRhYmxlUmVxdWVzdCIsImNhcmRMZXNzRGF0YUNhcmRUcmFjayIsInNlbmRNYWlsIiwicmVtb3ZlQ2FyZERlcG9zaXQiLCJsb2Fuc0lucXVpcnlXaXRoSnVyaWRpY2FsT3JkZXIiLCJnZXRMb2FucyIsImdldEJyYW5jaGVzIiwicGdQYXlCaWxsIiwibG9nb3V0IiwiZ2V0U2VsbFJlcG9ydCIsInBnTm9ybWFsVHJhbnNmZXIiLCJjYXJkTWFuYWdlbWVudCIsImhvdENhcmRCeVBpbiIsImdldERlcG9zaXRzIiwiY2FyZElzc3VpbmdBbGxvd2VkRGVwb3NpdHNUb09wZW4iLCJhY2hUcmFuc2FjdGlvblJlcG9ydCIsIm1hdGNoTmF0aW9uYWxDb2RlV2l0aE1vYmlsZU5vIiwibWF0Y2hOYXRpb25hbENvZGVXaXRoSWJhbiIsImNhcmRDaGFuZ2VQaW4iLCJjYW5jZWxDYXJ0YWJsZVJlcXVlc3QiLCJ1bmJsb2NrRGVwb3NpdFdpdGhKdXJpZGljYWxPcmRlciIsInBnQ2FyZFRyYW5zZmVyIiwiZ2V0Q2FyZE93bmVyIiwiYXV0b1RyYW5zZmVyIiwiY3VzdG9tZXJFeGlzdGVuY2VUb3RhbElucXVpcnkiLCJleHRlbmRlZENhcmRUcmFuc2ZlciIsIm5vcm1hbFRyYW5zZmVyUmVwb3J0IiwiZG9QYXltZW50IiwicmVnaXN0ZXJDaGVxdWVCb29rUmVxdWVzdCIsImxvZ2luIiwiYmxvY2tBY2NvdW50QW1vdW50IiwicmVzdW1lQWNoVHJhbnNmZXIiLCJjYXJkRXh0ZW5kIiwiZ2V0UmVxdWVzdFN0YXR1cyIsImNoYW5nZVN0YXR1c09mU21zT25saW5lRXZlbnQiLCJnZXRBdXRvVHJhbnNmZXJMaXN0IiwicmVzdW1lQWNoVHJhbnNhY3Rpb24iLCJnZXRTZWxsRGV0YWlsUmVwb3J0Iiwic3dpdGNoRnVuZFRyYW5zZmVyRnJvbVBoeXNpY2FsVGVybWluYWwiLCJnZXRUcmFuc2ZlckNvbnN0cmFpbnRJbmZvUGVyU2VydmljZSIsImNhbGN1bGF0ZUxvYW5FeHBlY3RlZEludGVyZXN0IiwiZ2V0VXNlclNNU1NldHRpbmciLCJjYXJkTGVzc0RhdGFDYXJkIiwiY2FyZFRyYW5zZmVyV2l0aE1vYmlsZU5vIiwicmVnaXN0ZXJDYXJ0YWJsZUJhdGNoVHJhbnNmZXJSZXF1ZXN0IiwibXVuR2V0UHJvZHVjdCIsIm11bkNhbGN1bGF0ZURlYnRCdXNCaWxsIiwiY2FzaENoZXF1ZSIsImlucXVpcnlJYmFuQWdlbmN5IiwiY29udmVydEliYW5Ub0RlcG9zaXROdW1iZXIiLCJjdXN0b21lckRlcG9zaXRJbnF1aXJ5V2l0aEp1cmlkaWNhbE9yZGVyIiwiY2hhbmdlVXNlcm5hbWUiLCJwZ1J0Z3NOb3JtYWxUcmFuc2ZlciIsImdldE1vZGVybkdhdGV3YXlSb2xlcyIsInVuYmxvY2tBY2NvdW50QW1vdW50IiwicGF5Q3JlZGl0QmlsbCIsImhvdENhcmQiLCJhY2hBdXRvVHJhbnNmZXIiLCJzZW5kU3RhdGVtZW50VG9FbWFpbE9yRmF4IiwiY2FyZExlc3NMaXN0Vm91Y2hlcnMiLCJnZXRPd25lckRlcG9zaXROYW1lIiwiZ2V0Q2FyZHMiLCJnZXREZXBvc2l0UmF0ZXMiLCJhZGRDYXJkRGVwb3NpdCIsImNoYXJnZUNhcmQiLCJwaWNoYWtJc3N1ZUNoZXF1ZSIsIm1hdGNoTmF0aW9uYWxDb2RlV2l0aEN1c3RvbWVyTm8iLCJnZXRTdGF0ZW1lbnQiLCJzZW5kUmV2ZXJzYWwiLCJjYXJkQmFsYW5jZUlucXVpcnlCeVN3aXRjaCIsImdldFBheW1lbnRQcmV2aWV3IiwiY2FyZFNlY29uZFBhc3N3b3JkSW5xdWlyeSIsInBlcnNpYW5DdXN0b21lckNsdWJBY3RpdmF0aW9uIiwiY3JlYXRlU21zUHJvZmlsZVNldHRpbmciLCJjYW5jZWxBY2hUcmFuc2ZlciIsInJlZ2lzdGVyQ2FydGFibGVUcmFuc2ZlclJlcXVlc3QiLCJibG9ja0RlcG9zaXRBbW91bnQiLCJnZXREZXBvc2l0Q3VzdG9tZXIiLCJmdWxsQmxvY2tBbmRSZWplY3RDcmVkaXREZXBvc2l0V2l0aEp1cmlkaWNhbE9yZGVyIiwiZGVmaW5lQ3VzdG9tZXJTaWduYXR1cmVTYW1wbGUiLCJnZXRDdXN0b21lckV4dHJhRGF0YSIsImNhcmRQdXJjaGFzZSIsImdldENyZWRpdERvc3NpZXJzIiwic2F2ZU9yVXBkYXRlU2Vjb25kUGFzc3dvcmQiLCJnZXRDYXJkTGltaXRhdGlvbnMiLCJiYXRjaFRyYW5zZmVyIiwicGF5QmlsbCIsImNvbnZlcnREZXBvc2l0TnVtYmVyVG9JYmFuIiwiZ2V0Q2FyZFByb2R1Y3RzIiwiYWNoVHJhbnNmZXJSZXBvcnQiLCJibG9ja0NoZXF1ZSIsImdldEFjY291bnRCYWxhbmNlIiwic3BlY2lhbFBheW1lbnQiLCJjdXN0b21lckV4aXN0ZW5jZUlucXVpcnkiLCJjYXJkQ29ycmVjdExpbmtlZEFjY291bnRzIiwiZ2V0RGVwb3NpdEJsb2NrSWQiLCJnZXRDaGVxdWVCb29rTGlzdCIsImdldEN1cnJlbmN5UmF0ZSIsImdldERlc3RpbmF0aW9uQ2FyZE93bmVyMiIsImdldFRyYW5zZmVyQ2hlcXVlTGlzdCIsImdldERlcG9zaXRzV2l0aE5hdGlvbmFsQ29kZUFuZE1vYmlsZU51bSIsInBheW1lbnRXaXRoVW5ibG9jayIsImxvYWRDb3JlUGFyYW1ldGVycyIsImdldENhcmREZXBvc2l0cyIsInRyYW5zZmVyRGVwb3NpdGVUb0NhcmQiLCJnZXRBdG1TdGF0dXMiLCJjaGFuZ2VQYXNzd29yZCIsImdldENhcmRTdGF0ZW1lbnRJbnF1aXJ5IiwidHJhbnNmZXJEZXBvc2l0ZVRvRGVwb3NpdGVMaXN0IiwicmVnaXN0ZXJDaGVxdWUiLCJhZGRQZXJpb2RpY0JhbGFuY2VSZXF1ZXN0IiwicmVnaXN0ZXJTZW1pUHJlc2VuY2VSdGdzIiwiY2FyZEJhbGFuY2VJbnF1aXJ5IiwiY3VzdG9tZXJJbnF1aXJ5V2l0aEp1cmlkaWNhbE9yZGVyIiwibXVuVHJhZmZpY1BsYXRlIl0sImNoYW5uZWxUeXBlIjoiU09GVFdBUkVfQUdFTlQiLCJpc0RpcmVjdERlYml0IjpmYWxzZSwiZXhwIjoxNjYzMzE0NTExLCJidXNzaW5lc3NCcmFuZE5hbWUiOiJ5YXJhbmtob3Jhc2FuIiwianRpIjoiYmM1NjkwNWMtYmQ4Ny00M2IwLTg3ZGMtM2Y4ZDE2ZmJjYTYxIiwiY3VzdG9tZXJObyI6IjgzOTczMzE3MjQ3MzcyMjYiLCJjbGllbnRfaWQiOiI4Mzk3MzMxNzI0NzM3MjI2IiwidXNlcm5hbWUiOiI4Mzk3MzMxNzI0NzM3MjI2In0.hrChqrWRkysyMdj4nW_T3kl41GLHdoU345ZYxEw7kUFIMFYq5IlCKyWmPQA2SFqrTzMg5yyBCRSoAN9lOGxmSu_aIC82cx2P-iTmjaTj7QS2F407WlHkF-tuyaf8xAhBdwaH7NMqbFuNBQL_iGvq_pfyxi9QnwYxtyf_BXYn5F1vpiUThAhDh_vM96GS0loBaj9FQx4vI_J9cXqociC7-NfqdNkSkDhjsi_zKT5SidagZelpeQlJCY3jhFg_xnid91r9eqQu8r8LcLDt6cOyuvzW1pYkzXRrBXKXharuuB0CoCUehcprle7r4IHK3M9r02Blbqr2fGAUZ68w8KnoKQ");
			request.setHeader("Content-Type", "application/json");
			request.setHeader("Cookie", "cookiesession1=678B28C9D27F95FCA8050568613A117A");
			request.setEntity(new StringEntity(joInput.toString(), "UTF-8"));

			HttpResponse response = httpClient.execute(request);
			BufferedReader rd = new BufferedReader(new InputStreamReader(response.getEntity().getContent()));

			StringBuffer sbResult = new StringBuffer();
			String line = "";
			while ((line = rd.readLine()) != null) {
				sbResult.append(line);
			}

			System.out.println(sbResult.toString());

		} catch (Exception e) {
			e.printStackTrace();
		}

	}

}