package ir.khalili.products.odds.core.enums;

public enum AccessLockIn {
	
	//OPERATOR
	NAS_OPERATOR_SAVE				,	
	NAS_OPERATOR_UPDATE				,
	NAS_OPERATOR_DELETE				,
	NAS_OPERATOR_SEARCH				,
	NAS_OPERATOR_FETCH_BY_AGENT_ID	,
	
	//AGENT
	NAS_AGENT_SAVE					,	
	NAS_AGENT_UPDATE				,
	NAS_AGENT_DELETE				,
	NAS_AGENT_FETCH_ALL				,
	NAS_AGENT_FETCH_BY_AGENT_ID		,
	
	//CONFIG
	NAS_CONFIG_UPDATE				,
	NAS_CONFIG_AGENT_UPDATE			,
	NAS_CONFIG_AGENT_SAVE			,
	NAS_CONFIG_AGENT_DELETE			,
	NAS_CONFIG_FETCH_ALL			,
	NAS_CONFIG_AGENT_FETCH_ALL		,
	
	//TASK
	NAS_TASK_FETCH_ALL_BY_OPERATOR_ID,
	NAS_TASK_FETCH_ALL,
	
	//CUSTOMER
	NAS_CUSTOMER_FETCH_ALL			,
	NAS_CUSTOMER_FETCH_ALL_BY_AGENT_ID,
	
	//REPORT
	NAS_REPORT						,
	
	//SERVICE
	NAS_SERVICE_UPDATE				,
	NAS_SERVICE_FETCH_ALL			,
	NAS_SERVICE_FETCH_ALL_BY_AGENT_ID,
	NAS_SERVICE_AGENT_UPDATE		,
	NAS_SERVICE_AGENT_FETCH_ALL		,
	;
	

}
