package ir.khalili.products.odds.core.enums;

public enum AccessLockIn {
	
	// COMPETITION
	OPP_COMPETITION_SAVE						,	
	OPP_COMPETITION_UPDATE						,
	OPP_COMPETITION_DELETE						,
	OPP_COMPETITION_FETCH_ALL					,
	OPP_COMPETITION_FETCH_BY_ID					,
	OPP_COMPETITION_QUESTION_ASSIGN				,
	OPP_COMPETITION_QUESTION_UNASSIGN			,
	OPP_COMPETITION_QUESTION_FETCH				,
	OPP_COMPETITION_RESULT_REGISTER				,
	OPP_COMPETITION_QUESTION_RESULT_REGISTER	,
	OPP_COMPETITION_POINT_CALCULATION			,
	
	// CONFIG
	OPP_CONFIG_UPDATE							,
	OPP_CONFIG_FETCH_ALL						,
	OPP_CONFIG_FETCH_BY_ID						,
	OPP_CONFIG_FETCH_BY_SYMBOL					,
	
	// FOLDER
	OPP_FOLDER_SAVE								,	
	OPP_FOLDER_UPDATE							,
	OPP_FOLDER_DELETE							,
	OPP_FOLDER_FETCH_ALL						,
	OPP_FOLDER_FETCH_BY_ID						,
	OPP_FOLDER_QUESTION_ASSIGN					,
	OPP_FOLDER_QUESTION_UNASSIGN				,
	OPP_FOLDER_QUESTION_FETCH					,
	
	// GROUP
	OPP_GROUP_SAVE								,	
	OPP_GROUP_UPDATE							,
	OPP_GROUP_DELETE							,
	OPP_GROUP_FETCH_ALL							,
	OPP_GROUP_FETCH_BY_ID						,
	OPP_GROUP_TEAM_ASSIGN						,
	OPP_GROUP_TEAM_UNASSIGN						,
	OPP_GROUP_TEAM_FETCH						,	
	OPP_GROUP_COMPETITION_FETCH					,
	
	// LEAGUE
	OPP_LEAGUE_SAVE								,	
	OPP_LEAGUE_UPDATE							,
	OPP_LEAGUE_DELETE							,
	OPP_LEAGUE_FETCH_ALL						,
	OPP_LEAGUE_FETCH_BY_ID						,
	
	// LOCATION
	OPP_LOCATION_SAVE							,	
	OPP_LOCATION_UPDATE							,
	OPP_LOCATION_DELETE							,
	OPP_LOCATION_FETCH_ALL						,
	
	// QUESTION
	OPP_QUESTION_SAVE							,	
	OPP_QUESTION_UPDATE							,
	OPP_QUESTION_DELETE							,
	OPP_QUESTION_FETCH_ALL						,
	OPP_QUESTION_FETCH_BY_ID					,
	
	// REPORT
	OPP_REPORT_REGISTERED_USERS_COUNT			,
	OPP_REPORT_COMPETITOR_USERS_COUNT			,
	OPP_REPORT_COMPETITOR_USERS_AMOUNT			,
	OPP_REPORT_ODDS_COUNT						,
	OPP_REPORT_CALCULATE_COMPETITION			,
		
	// TEAM
	OPP_TEAM_SAVE								,	
	OPP_TEAM_UPDATE								,
	OPP_TEAM_DELETE								,
	OPP_TEAM_FETCH_ALL							,
	OPP_TEAM_FETCH_BY_ID						,
	OPP_TEAM_IMAGE_UPDATE						,
	OPP_TEAM_MEMBER_SAVE						,
	OPP_TEAM_MEMBER_UPDATE						,
	OPP_TEAM_MEMBER_DELETE						,
	OPP_TEAM_MEMBER_FETCH_ALL					,
		
		
	// TRANSACTION
	OPP_TRANSACTION_FETCH_ALL					,
	OPP_TRANSACTION_REJECT						,
	OPP_TRANSACTION_CONFIRM						,
	OPP_TRANSACTION_SAVE						,
		
	// USER
	OPP_USER_FETCH_ALL							,
	OPP_USER_FETCH_BY_ID						,
	OPP_USER_FETCH_ODDS,
	OPP_USER_FETCH_QUESTION_ANSWER				,
	OPP_USER_FETCH_POINT_HISTORY				,
	;
	

}
