package ir.khalili.products.odds.core.enums;

public enum CustomerServiceStatus {
    REJECT,
    REGISTRY_OFFICE,
    IDENTIFICATION_UPLOAD,
    NATIONAL_CARD_UPLOAD,
    VIDEO_UPLOAD,
    PAYMENT,
    VALIDATE_INFO_BY_OPR,
    CONFIRM,
    DEFECT_DOC,
    SHIPMENT,
    RESIDENCE_INFO,
    JOB_INFO,
    SIGNATURE_UPLOAD,
    ACCOUNT_REQUEST,
    CUSTOMER_REGISTER,
    SABT_AHVAL

}
