package ir.khalili.products.odds.core.enums;

public enum ReportEnum {

	USERS_WITH_MAXIMUM_ODDS,
	ODDS_COUNT_PER_COMPETITION,
	USERS_COUNT_WITH_ODDS,
	QUESTION_STATISTIC_PER_COMPETITION,
	USERS_WITH_MAXIMUM_POINT,
	COMPETITION_WITH_MAXIMUM_ODDS,
	COMPETITIONS_TOTAL_POINT
}
