package ir.khalili.products.odds.core.enums;

public enum ReportEnum {

	
	REPORT_LEAGUE_USERS_WITH_MAXIMUM_POINT,
	REPORT_LEAGUE_BLOCKED_AMOUNT,
	REPORT_ALL_SECTION_ODDS_COUNT_PARTICIPANT_COUNT_TOTAL_POINT,
	REPORT_ALL_SECTION_CORRECT_ODDS_COUNT_AND_ODDS_PERCENTAGE,
	REPORT_THREE_SECTION_USERS_WITH_MAXIMUM_POINT,
	REPORT_LEAGUE_TRANSACTION_AMOUNT,
}
