insert into toppconfig (ID,NAME,SYMBOL,VALUE,TYPE,LEAGUE_ID) values(soppconfig.nextval,'قوانین و مقررات','TERMS_CONDITIONS','/app/odds/config/S_1665312994399.txt','File',1);
insert into toppconfig (ID,NAME,SYMBOL,VALUE,TYPE,LEAGUE_ID) values(soppconfig.nextval,'امتیاز هدیه اولیه','PRIMARY_GIFT_POINTS',100,'Number',1);
insert into toppconfig (ID,NAME,SYMBOL,VALUE,TYPE,LEAGUE_ID) values(soppconfig.nextval,'حداقل امتیاز هر سوال','MINIMUM_SCORE_QUESTION',10,'Number',1);
insert into toppconfig (ID,NAME,SYMBOL,VALUE,TYPE,LEAGUE_ID) values(soppconfig.nextval,'مبلغ بسته برنزی','AMOUNT_BRONZE_PACKAGE',200000,'Number',1);
insert into toppconfig (ID,NAME,SYMBOL,VALUE,TYPE,LEAGUE_ID) values(soppconfig.nextval,'مبلغ بسته نقره ای','AMOUNT_SILVER_PACKAGE',500000,'Number',1);
insert into toppconfig (ID,NAME,SYMBOL,VALUE,TYPE,LEAGUE_ID) values(soppconfig.nextval,'مبلغ بسته طلایی','AMOUNT_GOLDEN_PACKAGE',1000000,'Number',1);
insert into toppconfig (ID,NAME,SYMBOL,VALUE,TYPE,LEAGUE_ID) values(soppconfig.nextval,'امتیاز بسته برنزی','POINT_BRONZE_PACKAGE',10,'Number',1);
insert into toppconfig (ID,NAME,SYMBOL,VALUE,TYPE,LEAGUE_ID) values(soppconfig.nextval,'امتیاز بسته نقره ای','POINT_SILVER_PACKAGE',50,'Number',1);
insert into toppconfig (ID,NAME,SYMBOL,VALUE,TYPE,LEAGUE_ID) values(soppconfig.nextval,'امتیاز بسته طلایی','POINT_GOLDEN_PACKAGE',100,'Number',1);
insert into toppconfig (ID,NAME,SYMBOL,VALUE,TYPE,LEAGUE_ID) values(soppconfig.nextval,'شناسه لیگ فعال در پنل کاربری','ACTIVE_LEAGUE_ID',1,'Number',null);